# Generated by Django 3.2.18 on 2023-03-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_app', '0002_auto_20230331_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='other_details',
            field=models.TextField(blank=True, default="{'availability': 'Yes', 'notifications': 'On', 'language': 'English', 'dark_mode': 'Yes'}"),
        ),
    ]
