# Generated by Django 3.2.18 on 2023-03-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_app', '0003_user_other_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='other_details',
            field=models.TextField(blank=True, default={'availability': 'Yes', 'dark_mode': 'Yes', 'language': 'English', 'notifications': 'On'}),
        ),
    ]
