# Generated by Django 3.2.18 on 2023-04-03 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('in_app', '0004_alter_user_other_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=55)),
                ('street', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('postcode', models.IntegerField()),
                ('country', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=55)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='other_details',
            field=models.TextField(blank=True, default={'availability': 'Yes', 'dark_mode': 'No', 'language': 'English', 'notifications': 'On'}),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='in_app.address')),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='in_app.addresstype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
