# Generated by Django 3.2.18 on 2023-04-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('in_app', '0005_auto_20230403_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='building',
            new_name='address_line_one',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='street_line_two',
        ),
    ]
