# Generated by Django 3.2.18 on 2023-04-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('in_app', '0006_auto_20230403_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_line_two',
            new_name='address_line_two',
        ),
    ]
