# Generated by Django 3.2.18 on 2023-04-04 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('in_app', '0007_rename_street_line_two_address_address_line_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('mode', models.CharField(max_length=55)),
                ('status', models.CharField(max_length=55)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('repayment', models.ManyToManyField(default=None, to='in_app.Repayment')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(max_length=55)),
                ('picked_up_time', models.TimeField(default=None)),
                ('delivered_time', models.DateField(default=None)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='in_app.useraddress')),
                ('delivered_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivered_person', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='in_app.bookdeliveryslot')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='in_app.payment')),
                ('picked_up_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='picked_up_person', to=settings.AUTH_USER_MODEL)),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='in_app.pickupslotbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
