# Generated by Django 3.2.18 on 2023-04-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_app', '0008_order_payment_repayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='current_address',
            field=models.BooleanField(default=False),
        ),
    ]
